baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Toinen Kerros'

theme = "hugo-brewm" 


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

## Maybe we should do a nested menu for the main about too - so to involve more interaction within the history and process of the space
[[menu.main]]
  name = "About"
  url = "/About/"
  weight = 2

  [[menu.main]]
  name = "Calendar"
  url = "/Calendar/"
  weight = 3

  [[menu.main]]
  name = "Open Call"
  url = "/OpenCall/"
  weight = 3

## Nested Menu for Activities and other things - use it as a template 

[[menu.main]]
    identifier = "Activities"
    name = "Activities"
    weight = 4

    [[menu.main]]
        identifier = "Volunteering"
        name = "Volountering"
        pageRef = "/Volunteering"
        parent = "Activities"
        weight = 2

     [[menu.main]]
         identifier = "TK Ensemble"
         name = "TK Ensemble"
         pageRef = "/TKENSEMBLE"
         parent = "Activities"
         weight = 3


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
mainSections = ["posts"]

[params.logo]
    logoType = true


   ## Post display settings
    [params.posts]
        ## Enable text justification
        justifying = false
        ## Disable paragraph indentation
        noIndent = false
        ## Use sans-serif fonts as default
        sfdefault = false
        ## Show colophon section (including QR code)
        colophon = true
        ## disable redaction history
        disableHistory = false
        ## SHow related content
        related = true
        ## Show share buttons
        share = true
        ## enable section numbering
        secnum = false


